version: '3'
services:
  app:
    container_name: nextjs-app
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: posts
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # 如果你有初始化数据库脚本
    ports:
      - '3306:3306'